# Generated by Django 4.1.13 on 2024-03-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_grupo_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciale',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imagene',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('rol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=250)),
                ('num_view', models.IntegerField()),
                ('grupo_img_ref', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_base.categoria')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_base.usuario')),
            ],
        ),
    ]
